package com.estebancoloradogonzalez.listify.utils

object TextConstants {
    const val EMPTY: String = ""

    const val DATABASE_NAME: String = "listify_database"

    const val TABLE_BUDGET: String = "budget"
    const val TABLE_STATE: String = "state"
    const val TABLE_AMOUNT: String = "amount"
    const val TABLE_UNIT_OF_MEASUREMENT: String = "unit_of_measurement"
    const val TABLE_ESTABLISHMENT: String = "establishment"
    const val TABLE_PURCHASE_FREQUENCY: String = "purchase_frequency"
    const val TABLE_CATEGORY: String = "category"
    const val TABLE_USER: String = "user"
    const val TABLE_AMOUNT_UNIT_OF_MEASUREMENT: String = "amount_unit_of_measurement"
    const val TABLE_PRODUCT: String = "product"
    const val TABLE_SHOPPING_LIST: String = "shopping_list"
    const val TABLE_PRODUCT_ESTABLISHMENT: String = "product_establishment"
    const val TABLE_PRODUCT_PURCHASE_FREQUENCY: String = "product_purchase_frequency"
    const val TABLE_PRODUCT_CATEGORY: String = "product_category"
    const val TABLE_PRODUCT_SHOPPING_LIST: String = "product_shopping_list"
    const val TABLE_SHOPPING_LIST_STATE: String = "shopping_list_state"

    const val COLUMN_ID: String = "id"
    const val COLUMN_VALUE: String = "value"
    const val COLUMN_NAME: String = "name"
    const val COLUMN_SYMBOL: String = "symbol"
    const val COLUMN_REGISTRATION_DATE: String = "registration_date"
    const val COLUMN_UNIT_PRICE: String = "unit_price"
    const val COLUMN_IS_ACTIVE: String = "is_active"
    const val COLUMN_IS_READY: String = "is_ready"
    const val COLUMN_SHOPPING_LIST_DATE: String = "shopping_list_date"
    const val COLUMN_PURCHASED_AMOUNT: String = "purchased_amount"

    const val STATUS_ACTIVE = "Activa"
    const val STATUS_COMPLETED = "Completada"
    const val STATUS_CANCELLED = "Cancelada"

    const val UNIT_KILOGRAM = "Kilogramo"
    const val UNIT_KILOGRAM_SHORT = "kg"
    const val UNIT_POUND = "Libra"
    const val UNIT_POUND_SHORT = "lb"
    const val UNIT_LITER = "Litro"
    const val UNIT_LITER_SHORT = "L"
    const val UNIT_COUNT = "Unidad"
    const val UNIT_COUNT_SHORT = "u"

    const val STORE_D1 = "D1"
    const val STORE_DOLLAR_CITY = "Dollar City"
    const val STORE_BUTCHER = "Carnicería"
    const val STORE_GREENGROCER = "Verdulería"
    const val STORE_OTHER = "Otros"

    const val FREQUENCY_WEEKLY = "Semanal"
    const val FREQUENCY_FORTNIGHTLY = "Quincenal"
    const val FREQUENCY_MONTHLY = "Mensual"
    const val FREQUENCY_BIMONTHLY = "Bimensual"
    const val FREQUENCY_QUARTERLY = "Trimestral"
    const val FREQUENCY_FOUR_MONTHLY = "Cuatrimestral"
    const val FREQUENCY_SEMIANNUAL = "Semestral"

    const val PARAM_USER_ID: String = "userId"

    const val FRUITS = "Frutas"
    const val VEGETABLES = "Verduras"
    const val SPICES_AND_CONDIMENTS = "Especias y Condimentos"
    const val BEVERAGES = "Bebidas"
    const val GRAINS_AND_CEREALS = "Granos y Cereales"
    const val MEATS_AND_PROTEINS = "Carnes y Proteínas"
    const val DAIRY_AND_DERIVATIVES = "Lácteos y Derivados"
    const val BAKERY = "Panadería"
    const val SAUCES_AND_DRESSINGS = "Salsas y Aderezos"
    const val SWEETENERS = "Endulzantes"
    const val OILS_AND_FATS = "Aceites y Grasas"
    const val SNACKS = "Mecato"
    const val CLEANING_AND_HOME = "Limpieza y Hogar"
    const val PETS = "Mascotas"
    const val OTHERS = "Otros"

    const val TOTAL_EXPENDITURE = "Gasto Total: $"
    const val DATE_FORMAT = "dd/MM/yyyy"
    const val AMOUNT_FORMAT = "%,.2f"

}